# Generated by Django 5.1.3 on 2024-11-22 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mission", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("years_of_experience", models.PositiveSmallIntegerField()),
                ("breed", models.CharField(max_length=100)),
                ("salary", models.PositiveIntegerField()),
                (
                    "active_mission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cat",
                        to="mission.mission",
                    ),
                ),
            ],
        ),
    ]
